
project_id = "sportholic"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.fetch-youtube-data]
verify_jwt = false

[functions.generate-channel-content]
verify_jwt = false

[functions.generate-channel-keywords]
verify_jwt = false

[functions.generate-channel-metadata]
verify_jwt = false

[functions.update-channel-metadata]
verify_jwt = false

[functions.enhance-faceless-idea]
verify_jwt = false

[functions.generate-channel-type]
verify_jwt = false

[functions.take-channel-screenshot]
verify_jwt = false

[functions.fetch-channel-stats-apify]
verify_jwt = false

[functions.get-niches]
verify_jwt = false

[functions.add-niche]
verify_jwt = false

[functions.delete-niche]
verify_jwt = false

[functions.update-niche-details]
verify_jwt = false

[functions.initialize-storage]
verify_jwt = false
