
// A comprehensive list of niche options for YouTube channels
export const niches = [
  "Affirmation",
  "Animal",
  "Animation",
  "Archaeology",
  "ASMR",
  "Aviation",
  "Bad Neighborhood Tours",
  "Book Summaries",
  "Business",
  "Car",
  "Cash Stuffing",
  "Celebrity",
  "Comics",
  "Comedy/Funny",
  "Crime",
  "Cruises",
  "Cyrptocurrency",
  "Data Comparisons",
  "DIY",
  "Dinosaurs",
  "Documentary",
  "Documentary/List",
  "Drawing",
  "Drama",
  "Drones",
  "Economics",
  "Electric Cars",
  "Engineering",
  "Fighting",
  "Food",
  "Gaming",
  "Gaming History",
  "Gardening",
  "Geography",
  "Golfing",
  "Health",
  "History",
  "Home Gadgets",
  "Homework Help",
  "Investing",
  "Knitting",
  "Languages",
  "Life Hack",
  "List",
  "Lofi",
  "Lucid Dreaming",
  "Luxury",
  "Make Money",
  "Mindfulness",
  "Movie",
  "Mystery",
  "Narcissism",
  "NASCAR",
  "News",
  "Nostalgia",
  "Ocean",
  "Painting Timelapse",
  "Paper Airplanes",
  "Personal Finance",
  "Philosophy",
  "Piano",
  "Planner",
  "Politics",
  "Productivity",
  "Programming",
  "Psychology",
  "Real Estate",
  "Relationship",
  "Rollercoaster POV",
  "Scary",
  "Scary Story",
  "Science",
  "Scuba Diving",
  "Self Improvement",
  "Ships and Boat",
  "Spirituality",
  "Sports",
  "Tech",
  "Test",
  "Tours",
  "Travel",
  "Tutorials",
  "Vehicles",
  "Weird",
  "YouTube Growth"
].sort(); // Sort alphabetically for easier selection
